baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Engineering Management Journey'
theme = ["PaperMod"]

[params]
  description = "Thoughts, lessons, and reflections from my journey as an engineering manager"
  author = "pupersosition"
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
